server:
  host: "localhost"
  port: "8088"

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  database: "xiaozhe_ai"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
